import { motion, useInView } from "framer-motion";
import { useRef } from "react";
import step1 from "../assets/bstep 1.png";
import step2 from "../assets/bstep 2.png";
import step3 from "../assets/bstep 3.png";
import step4 from "../assets/bstep 4.png";
import clover from "../assets/clover.png";

const steps = [
  {
    title: "LIST YOUR SCRAP",
    description:
      "Begin by listing the scrap generated by your business on our platform. Provide details such as type (metal, paper, plastic, e-waste, etc.), quantity, and location. Our intuitive interface makes it quick and easy to upload this information, ensuring the right merchants are notified about your scrap availability.",
    image: step1,
  },
  {
    title: "COMPETITIVE BIDDING",
    description:
      "Once your scrap is listed, verified scrap merchants in our network place competitive bids for it. This process ensures you get the best market rates, fostering transparency and helping you maximize the value of your scrap. Review bids in real-time and select the one that best meets your expectations.",
    image: step2,
  },
  {
    title: "SCRAP COLLECTION",
    description:
      "After accepting a bid, the selected merchant coordinates with you to schedule a convenient pickup time. Our platform ensures that all merchants and logistics partners are verified, providing a smooth and reliable collection process tailored to your business needs.",
    image: step3,
  },
  {
    title: "TRADE YOUR SCRAP",
    description:
      "Once the scrap is collected, the transaction is completed seamlessly. You receive payment promptly as per the agreed bid. By using Ecomitra, your business can efficiently trade scrap while contributing to a circular economy and sustainable waste management.",
    image: step4,
  },
];

const StepsSection2 = () => {
  return (
    <section className="bg-[#1C211B] text-white px-6 lg:px-20 pt-24 pb-24 flex flex-col items-center">
      {/* Header Section */}
      <div className="flex flex-col gap-8 justify-between items-center mb-16 w-full max-w-5xl md:flex-row">
        {/* Left Text Section */}
        <motion.div
          initial={{ opacity: 0, x: -100 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="mb-4 md:w-2/3"
        >
          <h2 className="mt-10 text-3xl font-bold md:text-4xl">
            Ecomitra’s Business:
          </h2>
          <div className="mt-2">
            <h2 className="text-[#26B33B] text-3xl md:text-4xl font-bold relative inline-block">
              Revolutionizing Industrial Waste Management
              <span className="block h-[1px] bg-white w-full mt-3"></span>
            </h2>
          </div>
          <p className="mt-4 text-base text-gray-300">
            Ecomitra’s business service connects industries with a network of
            scrap merchants, enabling efficient, transparent recycling and
            waste management. By facilitating the recycling of scrap materials,
            we help businesses reduce their environmental footprint, conserve
            resources, and lower disposal costs.
          </p>
          <p className="text-[#26B33B] mt-2 text-base font-medium">
            Ecomitra’s B2B model fosters sustainability by connecting industries
            with scrap merchants for efficient recycling, reducing waste, and
            promoting a circular economy.
          </p>
        </motion.div>

        {/* Right Image */}
        <motion.div
          initial={{ opacity: 0, x: 100 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="flex justify-center md:w-1/3"
        >
          <img
            src={clover}
            alt="Clover"
            className="w-50 h-50 rounded-full bg-[#A7E85A] p-0"
          />
        </motion.div>
      </div>

      {/* Steps Section */}
      <div className="space-y-16 w-full max-w-5xl">
        {steps.map((step, index) => {
          const isEven = index % 2 === 0;
          const ref = useRef(null);
          const inView = useInView(ref, { once: true, amount: 0.3 });

          return (
            <motion.div
              ref={ref}
              key={index}
              initial={{ opacity: 0, x: isEven ? -100 : 100 }}
              animate={inView ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.8, delay: 0.2 }}
              className={`flex flex-col md:flex-row ${
                isEven ? "md:flex-row" : "md:flex-row-reverse"
              } items-center md:items-start gap-8`}
            >
              <div className="flex-1">
                <h3 className="text-[#26B33B] text-2xl font-bold">
                  STEP {index + 1}
                </h3>
                <p className="text-base font-semibold text-gray-300">
                  {step.title}
                </p>
                <div className="border-b border-[#26B33B] w-20 my-2"></div>
                <p className="text-base text-gray-300">{step.description}</p>
              </div>
              <div className="flex-1">
                <img
                  src={step.image}
                  alt={`Step ${index + 1}`}
                  className="w-full rounded-xl"
                />
              </div>
            </motion.div>
          );
        })}
      </div>
    </section>
  );
};

export default StepsSection2;
