import clover from "../assets/clover.png";
import step1 from "../assets/bstep 1.png";
import step2 from "../assets/bstep 2.png";
import step3 from "../assets/bstep 3.png";
import step4 from "../assets/bstep 4.png";

const StepsSection2 = () => {
  return (
    <section className="bg-[#1C211B] text-white px-6 lg:px-20 pt-24 pb-24 flex flex-col items-center">
      <div className="w-full max-w-5xl flex flex-col md:flex-row items-center justify-between gap-8 mb-16">
        {/* Left Text Section */}
        <div className="md:w-2/3 mb-4">
          <h2 className="text-3xl mt-10 md:text-4xl font-bold">Ecomitra’s Business:</h2>
          <div className="mt-2">
            <h2 className="text-[#26B33B] text-3xl md:text-4xl font-bold relative inline-block">
             Revolutionizing Industrial Waste Management
              <span className="block h-[1px] bg-white w-full mt-3"></span>
            </h2>
          </div>
          <p className="text-gray-300 mt-4 text-base">
          Ecomitra’s business service connects industries with a network of scrap merchants, enabling efficient, transparent recycling and waste management. By facilitating the recycling of scrap materials, we help businesses reduce their environmental footprint, conserve resources, and lower disposal costs. Through our platform, companies can participate in the circular economy, turning waste into valuable resources and promoting sustainability across industries. Ecomitra makes it easy for businesses to contribute to a greener future while improving their bottom line.
          </p>
          <p className="text-[#26B33B] mt-2 text-base font-medium">
          Ecomitra’s B2B model fosters sustainability by connecting industries with scrap merchants for efficient recycling, reducing waste, and promoting a circular economy.
          </p>
        </div>

        {/* Right Image */}
        <div className="md:w-1/3 flex justify-center">
          <img
            src={clover}
            alt="Clover"
            className="w-50 h-50 rounded-full bg-[#A7E85A] p-0"
          />
        </div>
      </div>

      {/* Steps Container */}
      <div className="w-full max-w-5xl space-y-16">
        {/* Step 1 */}
        <div className="flex flex-col md:flex-row items-center md:items-start gap-8">
          <div className="flex-1">
            <h3 className="text-[#26B33B] text-2xl font-bold">STEP 1</h3>
            <p className="text-gray-300 font-semibold text-base">
              LIST YOUR SCRAP
            </p>
            <div className="border-b border-[#26B33B] w-20 my-2"></div>
            <p className="text-gray-300 text-base">
            Begin by listing the scrap generated by your business on our platform. Provide details such as type (metal, paper, plastic, e-waste, etc.), quantity, and location. Our intuitive interface makes it quick and easy to upload this information, ensuring the right merchants are notified about your scrap availability.
            </p>
          </div>
          <div className="flex-1">
            <img src={step1} alt="Step 1" className="rounded-xl w-full" />
          </div>
        </div>

        {/* Step 2 */}
        <div className="flex flex-col md:flex-row-reverse items-center md:items-start gap-8">
          <div className="flex-1">
            <h3 className="text-[#26B33B] text-2xl font-bold">STEP 2</h3>
            <p className="text-gray-300 font-semibold text-base">
            COMPETITIVE BIDDING
            </p>
            <div className="border-b border-[#26B33B] w-20 my-2"></div>
            <p className="text-gray-300 text-base">
            Once your scrap is listed, verified scrap merchants in our network place competitive bids for it. This process ensures you get the best market rates, fostering transparency and helping you maximize the value of your scrap.
            Review bids in real-time and select the one that best meets your expectations.
            </p>
          </div>
          <div className="flex-1">
            <img src={step2} alt="Step 2" className="rounded-xl w-full" />
          </div>
        </div>

        {/* Step 3 */}
        <div className="flex flex-col md:flex-row items-center md:items-start gap-8">
          <div className="flex-1">
            <h3 className="text-[#26B33B] text-2xl font-bold">STEP 3</h3>
            <p className="text-gray-300 font-semibold text-base">
            SCRAP COLLECTION
            </p>
            <div className="border-b border-[#26B33B] w-20 my-2"></div>
            <p className="text-gray-300 text-base">
            After accepting a bid, the selected merchant coordinates with you to schedule a convenient pickup time. Our platform ensures that all merchants and logistics partners are verified, providing a smooth and reliable collection process tailored to your business needs.
            </p>
          </div>
          <div className="flex-1">
            <img src={step3} alt="Step 3" className="rounded-xl w-full" />
          </div>
        </div>

        {/* Step 4 */}
        <div className="flex flex-col md:flex-row-reverse items-center md:items-start gap-8">
          <div className="flex-1">
            <h3 className="text-[#26B33B] text-2xl font-bold">STEP 4</h3>
            <p className="text-gray-300 font-semibold text-base">
            TRADE YOUR SCRAP
            </p>
            <div className="border-b border-[#26B33B] w-20 my-2"></div>
            <p className="text-gray-300 text-base">
            Once the scrap is collected, the transaction is completed seamlessly. You
receive payment promptly as per the agreed bid. By using Ecomitra, your
business can efficiently trade scrap while contributing to a circular economy
and sustainable waste management.
            </p>
          </div>
          <div className="flex-1">
            <img src={step4} alt="Step 4" className="rounded-xl w-full" />
          </div>
        </div>
      </div>
    </section>
  );
};

export default StepsSection2;
